[[GAP]]
arch = "aarch64"
git-tree-sha1 = "e4de9c62f857c0c0c58f7dc8c13e0a9f1d345f5b"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "9bf4d94e821de7011df33be555e51d264bf8e376b2c17dabfc999bd9e07e1002"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v4.11.0+1/GAP.v4.11.0.aarch64-linux-gnu.tar.gz"
[[GAP]]
arch = "aarch64"
git-tree-sha1 = "7aed4d680fb2cb483a92672e834be36af6c6358b"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "ae1a07c234a3066efb6b4148c93d21a4e8d8232bb9995b634feffb9c26bcb958"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v4.11.0+1/GAP.v4.11.0.aarch64-linux-musl.tar.gz"
[[GAP]]
arch = "powerpc64le"
git-tree-sha1 = "8e1501a80767dd5d6893dbe4cd78ea78c0942ce2"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "bc14ab6f62a6c2485137cc17f66c7c450bd0759574832d6951cb8dde011f8c2e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v4.11.0+1/GAP.v4.11.0.powerpc64le-linux-gnu.tar.gz"
[[GAP]]
arch = "x86_64"
git-tree-sha1 = "83fc4da57c6df4e6b16f3e4b70c3bfcd4678df08"
os = "macos"

    [[GAP.download]]
    sha256 = "c073af4b2a3da22a992517588c5e5c9fdd5c086bf374f3ffe56422ff3033e746"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v4.11.0+1/GAP.v4.11.0.x86_64-apple-darwin.tar.gz"
[[GAP]]
arch = "x86_64"
git-tree-sha1 = "6c85266e2503698bd3eb5b6ed5545c8f5240eca3"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "e55a1d7642c3780e5792ddc5289c01815f2c9ddd4606e371c83da2ee9b0b2254"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v4.11.0+1/GAP.v4.11.0.x86_64-linux-gnu.tar.gz"
[[GAP]]
arch = "x86_64"
git-tree-sha1 = "ae2c11e0e371d3c16d4b2dab368ca6413b3afab7"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "70cc5025a8c261f113407f7af17f159f38367112ffa741f77a625e541e597743"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v4.11.0+1/GAP.v4.11.0.x86_64-linux-musl.tar.gz"
[[GAP]]
arch = "x86_64"
git-tree-sha1 = "757494c3268624465266bcb52e6b8ca2d6e8f46c"
os = "freebsd"

    [[GAP.download]]
    sha256 = "e6ee8bb5cccb3fb9db722f00e4bbca5a7db919c708c1b745d9afb258a84b3fdd"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v4.11.0+1/GAP.v4.11.0.x86_64-unknown-freebsd.tar.gz"
