[[GAP]]
arch = "aarch64"
git-tree-sha1 = "39dd9b70dac6d06cc9e2c4696109abb8ceae034a"
julia_version = "1.7.0"
os = "macos"

    [[GAP.download]]
    sha256 = "9b8b977fc4f2abd2c895401574da92afc2e45debb704180a4fe0cf0be0bbe215"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.aarch64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "aarch64"
git-tree-sha1 = "0530e061b9125312b1231bb9a6ecb1fe136bddb7"
julia_version = "1.8.0"
os = "macos"

    [[GAP.download]]
    sha256 = "1fb8dc2eb8ccccd27c80af27d183cdf0a3b7756326753ab89be00ab7d7d96ee5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.aarch64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "15e7d5a59bc89ff833fdaf1498208fe72e3eff17"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "ac863f1defd5a3f1e2c5ebb3d33af53f6d5499a9e7b3ade557952d067f39ca79"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.aarch64-linux-gnu-cxx03-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "60c404b5c4863b9e00f8a9453017e9464338ea6e"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "c1663e4b1ce59199ae27666c0acb7cd641cc081e72804f548d8403b1931f8fde"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.aarch64-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fc5469b7b285de5c6c1730497eddbc0d275fc63a"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "691fe3812a08f9d20d6e4ddac864385061f176bb990518d5575a21aa67de6334"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.aarch64-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6cc3ff3bc7b37b382f506b57e63c0de2ca2e5121"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "0220096e07d40fcb3c459d9148edbe1dc83d57d3c7b64848694371ae0d08e455"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.aarch64-linux-gnu-cxx11-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1117bd2eec0704793e6d055d590202502bfc2f07"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "5959d1e33bd2f4605eb35d86152ff162007feb0e29c66cbd255f97fe67a3f784"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.aarch64-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "31b1956b3105fbf051d2dc828d8863a3daa313ec"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "82f1484bf8a8684c0349f127402495fb1f595cef76eae67acb30f4389f269e96"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.aarch64-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3e9d771feabede984e8d2a97374c299e7e72b7fe"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "e1c98b7048717b260308bdcc2b158a9c379335addc837d63475ad02868e450f8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.aarch64-linux-musl-cxx03-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1087fe734787d49c4345c74665fd24e0817878a1"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "5ae0ef9163520ca2107f9c4a857ba5a75de18e63043f4d267db07a345ed2d42a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.aarch64-linux-musl-cxx03-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84586eae7ecc4c39da9a9e0446feb40bf8c5dcd1"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "df82cd7eb06923255cf5d4a8286333718d1a5f001a1822c045be156d63d3e737"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.aarch64-linux-musl-cxx03-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "067dafce4e737e20f7983309fcae4ef3bf145640"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "a31900cc81977837cfd4e0481f8c99eb501bc45038b25f777d31cb9e5f5ca1d2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.aarch64-linux-musl-cxx11-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "44ec638eeae075d148aba8e0984dcddfa8f843fc"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "81e688a880620845dc1ba7a2228ab569a56b6c8261486bfa8711f0e997aab122"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.aarch64-linux-musl-cxx11-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b8d6b59200db7972779a3ec5e86202243a493bc1"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "82e4e12c3fc64815c89ae05d09f4c6e33aa657272597ef7760a0f025c47055a7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.aarch64-linux-musl-cxx11-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b94a7e7e5805ae518ec5fb45824904cb968f62b1"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "92e2eb6999870785505c17d2cbb83b8430dd9611fb071a4ba41b14d31e2d30b4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.powerpc64le-linux-gnu-cxx03-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fb7ad28d200fac8b1570898d608891ea566c61aa"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "c4e8574b7891b10d30b4082fe4013935167be5cb2d03aa4dcbef17eb71cf72a7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.powerpc64le-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2f90d85fa8383944cdcd9943ee09f550a8537047"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "c763bcc0f62244ae390f5d01cb75e1d673cf0e20a9f26daa2314c8c81c3fd884"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.powerpc64le-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2dbc5bee0f25842bbd4371a1493cae9ce7c59fab"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "b91e8dba222d815a96a3b4fc0f31f4213eec370b9334f0a10f8b07dc835c2386"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.powerpc64le-linux-gnu-cxx11-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e4dd87c987090430fd29ca169708c317d845e89"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "45effc777dd71801dcdf59ce4a216c19489e5b5507f0f29a11070259234ab5bc"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.powerpc64le-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d61f50910ee782c7ea6bf9ed379ce97c7a4e8aa"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "dff59e9f984310325f9a49786b878ed4eb5868ac38f00c1b217be14a3f551b28"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.powerpc64le-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "x86_64"
git-tree-sha1 = "5fdefcf04be5e2fdc5403980debc6fa804b7d995"
julia_version = "1.6.0"
os = "macos"

    [[GAP.download]]
    sha256 = "043f4fa6298390ffcead161738969362d56d509da046e9c535c2110581d423c7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.x86_64-apple-darwin-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "x86_64"
git-tree-sha1 = "8ef767e6a79f9fd57c2e2969a4186ea0570cbfb4"
julia_version = "1.7.0"
os = "macos"

    [[GAP.download]]
    sha256 = "8c0ffad33d6ae74ba85c96b41c5c6f505d009af72fefabdae15b08aba88f5698"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.x86_64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "x86_64"
git-tree-sha1 = "7f89d6407967ea5eb2bd411b38f70c84c93c387d"
julia_version = "1.8.0"
os = "macos"

    [[GAP.download]]
    sha256 = "e3c95c8afadf03889856bb4414591dbd6f401de38369bfe0206625ef8b839f50"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.x86_64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2920c5c6efe72835b38ec64406f59b0ef5ac8900"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "749add6b93b1362f39e94d04fa48f91d703294dca5ab91d7b81fbc1d99be7c7e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.x86_64-linux-gnu-cxx03-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "489be7c1d20770ee042d79edf9f072303b4f35e0"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "f69e7e3c3f941411501c7978d1420999675246834c5ce9f08bc681681b4182b0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.x86_64-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a26a847fa8877ef3603aef2d39ae14eb7da2a0e"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "f97720aa9fe999c877c1aaab64e6b41b127aa43dbe84021cc55e07ddb01e2f93"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.x86_64-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "937021422f8e82f8f0dcf09881e9db548e9c6661"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "96c53991716d1fc4d328b728a82b5a627a330fd04cce38640dd7c13ed4f1e338"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.x86_64-linux-gnu-cxx11-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "106bc2c1ec003379a56f544ee87ba232e4221168"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "ce24072aa5391e44bc0116551455f7b72272a6d77d7e8b11b2bc7dee3fb57aa5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.x86_64-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e63bbd266e09f1fffad7fbdb819dbc2aca1725b9"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "27fb271d8fd6ef2b7a7fe85ebc45facf6dacf8c525f56931c6033404883c82ed"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.x86_64-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "147ee54fb8c0fd529ce1b84d4a503eab13968606"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "50431955090b7fed8d4076bb0212746cdf65add721cbb43675dbedcf86e0ceff"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.x86_64-linux-musl-cxx03-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c0a6a887d1b5a11c132c0691ff89375c072af7e"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "6ddfca8a6ef2c8fc61b28552fa4882c4a16bd23b92f42bfdc575f1b91e6a4dad"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.x86_64-linux-musl-cxx03-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b919b6e5a335073d7ae996ad4a1b6c2569d5210d"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "4fec0f5e7cdc347cc0b64298b64d1d3e8786563b0e3673de62cf4eb7aec04d7d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.x86_64-linux-musl-cxx03-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e46f49c403c62b4dc55a7f76b1bc1f0ac8d8900"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "2675c69ba30b1b20c35ccfce3ba6859b7d5fb43f3e82a453771fd79a595798f7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.x86_64-linux-musl-cxx11-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e1e1de8ce731e61fcc585a6e4f9ff0784101c0e0"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "c4e5897b4ade4bb032079b9fde2e3941f9b26a3802ff1749ab8a7464b289e6a6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.x86_64-linux-musl-cxx11-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f9caadd9bb553c1eefec659a16de0bb3d06c82fb"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "20ef495668f3ff160b9e440cd9267806a1b926135f363e17b0dd0e17fded4965"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.x86_64-linux-musl-cxx11-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "x86_64"
git-tree-sha1 = "2a40058578e019b07090ccdfa8838974be22ee5a"
julia_version = "1.6.0"
os = "freebsd"

    [[GAP.download]]
    sha256 = "506a99ac3064d2f2790c9891098fe7d95324935986d193e684707faf5ef339eb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.x86_64-unknown-freebsd-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "x86_64"
git-tree-sha1 = "e3985183f8847434e00462a2d86741952747e45b"
julia_version = "1.7.0"
os = "freebsd"

    [[GAP.download]]
    sha256 = "40e14bd4304cab39f27401c094e182ce63fd592d66c666b471535c1feb1a1904"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.x86_64-unknown-freebsd-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "x86_64"
git-tree-sha1 = "03f6dd62775130d36a7f04bec6d24640b14ebdee"
julia_version = "1.8.0"
os = "freebsd"

    [[GAP.download]]
    sha256 = "7fa899f0d17c110d1607133b065e057029dbada3c61699dfd56fe2c6afbf0be2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+0/GAP.v400.1191.1.x86_64-unknown-freebsd-julia_version+1.8.0.tar.gz"
