[[GAP]]
arch = "aarch64"
git-tree-sha1 = "5eade37b657df272fca285491ac17f62417f1ded"
julia_version = "1.7.0"
os = "macos"

    [[GAP.download]]
    sha256 = "30781f950732071d885e680dbe37bbcae5ef4c5db67b5afd0f8abae9a6bc0651"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.aarch64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "aarch64"
git-tree-sha1 = "3b2b829ef6eaefda682ee1b31205b73dd2df3f65"
julia_version = "1.8.0"
os = "macos"

    [[GAP.download]]
    sha256 = "77fe26e0d54fe2ad840316763cc9e50f41d6a630bbc618069b541c7068582453"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.aarch64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c0dd7475b61543765016bf9da2ccad52e92e1f1a"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "24b6079e43c7ce5c24704e7a8a3c94ee095688562131a50ff8d7134878ada5e2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.aarch64-linux-gnu-cxx03-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1cd82006d1fac25bc18c50b5df6a12c6eb59c7fb"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "9d131b483972853fb9168ed29bf55b807c05be8f573cddc3bcae2fc5dccc5994"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.aarch64-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "555ba32b0d1ca156b26cdf4bf9f3b5363c18d532"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "e8ec2451da84dc6e249343645394be22343ce7fb39b8dd34d97011b789420a61"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.aarch64-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f26021d97160ecf26b56ec0044bbc14169051b5"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "85b9a10ac9d13d309b8fe87e8d3a2df6d6daaf8e61e771c9212e340b36623e8a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.aarch64-linux-gnu-cxx11-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "069a6d7754f7af78b6c2598ad2aef99aa5c0fb94"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "04109393ccc22ff4b5bb85ca248f6a9584b70b7480a7bbc5d62ad4ccc1f08e91"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.aarch64-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f01e130b0358eff66ec4f5dcd8c007f7c2d1ad33"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "a0f5ae63c5936da320311855b81a78e974b360351d139d94c5925e6077f5ac5d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.aarch64-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dbac8c26651206f74d528d152b0f86138fc6d883"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "32393cfd733fe4e951ea6311a83439af86caeede03324aac558b71aaba32e00a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.aarch64-linux-musl-cxx03-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "66316597c3d62e85dd35866f4306cbbdb159938f"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "aa03ca2e1e03a464a8c4f39f0a64fd4d1d599c79eea643e86f55a72329b53290"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.aarch64-linux-musl-cxx03-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f6e2b6f93e9f70223371538cdd5be1ef67ffa170"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "f380504224125f3b0314cc989c3d0655f79b08b5823303a0b0063628a5e55c24"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.aarch64-linux-musl-cxx03-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94bc0764f7187bb526ae93ad6927c7e107faac12"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "bf082a1603cef08b13a11ca42e0c8405d70d167e76ea1df626e14feb6c6def98"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.aarch64-linux-musl-cxx11-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fefe0c12c1efd9c82481873bcfadcb9c8ef350e2"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "c95ec074288e8dae8dfe3476b2ccb82c11a5a100a3249d4fdf203531498c5ce5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.aarch64-linux-musl-cxx11-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58343c7794367e3ef4efa9d510a8cab4c0572ac8"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "59335dd2c3f754b0d808697a042150fc7416d2ebb6681b2c243f64307612e465"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.aarch64-linux-musl-cxx11-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "95f056e1147bf0d3672f94a9577ed5e12f996664"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "3920e1e574e0ef06a64e277bd8654af3cad45fa2acfe433a25c9599c98cbcf30"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.powerpc64le-linux-gnu-cxx03-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1c8a3badf928c9317da930515aadaa9661957e15"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "74d5a9c0d9d14947f929777849340935034005948fb247abded5f83f7e243919"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.powerpc64le-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d56a99a17bddc2c509fd27530915fe1ae1dba8a"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "9fae9adfbb066bae54b4e60699374922715d6fd5a377847acb06b0c4b115c9e2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.powerpc64le-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5f749ce59bea373222ba654ebefad441ead61ac"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "94e072e9e2193abfa5546998df3f03cc7365136f91cd961537311e04221b2095"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.powerpc64le-linux-gnu-cxx11-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc78b79f4168497ec67ef9e1912f5a5fe74b0fa1"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "6e5149b00189f3ae305287dc3ec628dff54e9302cfd68a1c3f3ebd600add2ee2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.powerpc64le-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "33391a4728fc7cfad726a372e9222c855f064ea2"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "84226e6cc98ce7b56e25b3da47b02e217e7928c9458273b40f8509ef038a5205"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.powerpc64le-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "x86_64"
git-tree-sha1 = "118a9897b9e0d9ce4fa5036f57d758892f583590"
julia_version = "1.6.0"
os = "macos"

    [[GAP.download]]
    sha256 = "19dc2c2c108a28bd3cc3215c4aa1226d53a3fdae95a034e0280f24b7011ff5b7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.x86_64-apple-darwin-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "x86_64"
git-tree-sha1 = "dfce2ef417b608d272a0f6149a1beddef53c50b3"
julia_version = "1.7.0"
os = "macos"

    [[GAP.download]]
    sha256 = "26923cf09efd8bfc270b32485f69c8799a7110eaa580f8864784ed282cabcf97"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.x86_64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "x86_64"
git-tree-sha1 = "814b2fb21cea0d44328952553a2dcb8ce7724b44"
julia_version = "1.8.0"
os = "macos"

    [[GAP.download]]
    sha256 = "a4192f2ae0362d870e484b3630364aae7b0a65b9bd3890c946d14f8a68e50816"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.x86_64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "67d155618844d1ba709d1429b62cf550cc7f269c"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "c7ba672f2ab8c97479dc75c3d0fd516cfc400d4bf915df83665929e4f8ed3410"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.x86_64-linux-gnu-cxx03-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "213230544a67c649f80f636281589baf151d6cfc"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "f352aba3dff45fd277e62ffcac5c1b611f964ce3e71cc310405e8afc8affa6da"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.x86_64-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "14b2798c8c8374df90822e763a0bb018b6772993"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "e9eb92b8e80bcbfd77c3d1d8531c16bb39cbdeed640819f21264d1f8a129f2b2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.x86_64-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1eaca615a377bddac560cd2b2ff8f2f05f555225"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "8171c13b9faeb3512be4cc68e98fbd2d1a80a721d77312facd342e942caa3346"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.x86_64-linux-gnu-cxx11-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13eda4e4f6e49979f510fb266fe2d31adc8b10af"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "4315f232ebbb4334f15afe0d6719c63b8d07ec2fa9d82757fb7bfb8d2f396ab2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.x86_64-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d4ea016ad4165fdbf16fb88f310493fc44759b9"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "debfdf89c62f8f3e5fc5a46b5ea3bfa1687e155bfb2bacee87c90f594326f20d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.x86_64-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d56eee4ce07ef48048341c8667416ca644f7aae9"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "4b5bb6f278c2759652dd7de36bd9ff069bafe34fd67a63236fe22747bb7b25b4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.x86_64-linux-musl-cxx03-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d758c77ede6d7a6c6955944b1b27a3e940cc99ed"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "fcb102902057ddc2ea23db87953730d3bc82d4e85cb36b34e54ef0593e4d6b7f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.x86_64-linux-musl-cxx03-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "909678b43b8a05505c45c4309c75778d30c77b40"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "05dda7a1fba05837ba54b1301d894654eff4d534958e7b3d108826655ffc06a1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.x86_64-linux-musl-cxx03-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95da94b9519b973fe90749f1a3c03550986e5bc6"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "0d588bb1262cbb666b7cbc9254e9e5de059df8090516e63ac540c15bdfaa8ca3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.x86_64-linux-musl-cxx11-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4eae62f2a75fbc189ee8f30e8f4e511eb5b7bef"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "68f366f29b1efe00fc9eb5434b7447c1fb87b796dc7828e453d0f5ec930a91cc"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.x86_64-linux-musl-cxx11-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f235ddc173592f5fc49190b3e09391a6d3b8884"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "c5fae3228368d7ee8b6f98644e54ce8d843cfdec313da26b700064d11e1d78d8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.x86_64-linux-musl-cxx11-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "x86_64"
git-tree-sha1 = "258be8b83ed6875e80fbc274b3e51bc92b58ef9d"
julia_version = "1.6.0"
os = "freebsd"

    [[GAP.download]]
    sha256 = "30843329cce4a44eab251ce4f13762064de721db3072fdb67f65ed30bcebbbb2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.x86_64-unknown-freebsd-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "x86_64"
git-tree-sha1 = "5e5dd2be79834004e6664d23ca147288c356b530"
julia_version = "1.7.0"
os = "freebsd"

    [[GAP.download]]
    sha256 = "470ca96f94563adf029c85e1e2de45d6ac936e85f236f78d29cbf4e65d9a6cc0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.x86_64-unknown-freebsd-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "x86_64"
git-tree-sha1 = "8335315e0ac15c2275050bb2d1a1b8b96bb08262"
julia_version = "1.8.0"
os = "freebsd"

    [[GAP.download]]
    sha256 = "4991b457c1543b7c92a67972530cc0f71fe4fd1c994c1bdc0a3e4b0a661aa042"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.0+0/GAP.v400.1191.0.x86_64-unknown-freebsd-julia_version+1.8.0.tar.gz"
