[[GAP]]
arch = "aarch64"
git-tree-sha1 = "205e850adbe0d3f4ec80fde83608138653e08f50"
julia_version = "1.7.0"
os = "macos"

    [[GAP.download]]
    sha256 = "a1aa56f9e86627a3eb02a78e78b3fcf891f942aba64690bf7940f95e2eea782f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.aarch64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "aarch64"
git-tree-sha1 = "f1352583a935106b0581cb84e6b8edd5d9872b2a"
julia_version = "1.8.0"
os = "macos"

    [[GAP.download]]
    sha256 = "74652cadfd9d04de3a438d347b9f3d9aff7507bf7afca32be07f7eee130cad0c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.aarch64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "62d32aadbf5233f3ad21ea7325cce8b43dc7b13d"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "7e44a99f06db20762dba8fe958e013521fb250218afb81feafcd5683948bcba3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.aarch64-linux-gnu-cxx03-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a694ac332e94a5bc54e187d56ab20357c83587e8"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "1643466bd333a6abfd65e48fb72c17894808543f26fe8649409904684e1b8b9f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.aarch64-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "659fc0ec1940bb2730abcd25316056416e4273ce"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "90b7dbff2ad2f3bba5a746f35f91451cc6cc9737d68843ff7c3b47de57e1a5bb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.aarch64-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d64cb03c22c9d778fe6b1fc85fc8ce1a45beb72"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "ad980484ae01c593a75a730dd5a6654572cf788594d25ecff4acb924fba30da6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.aarch64-linux-gnu-cxx11-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a105756d351447a5f2681f6c384d3e88ae95d99"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "e8b57117c1cb684a84183fa9440ec1302677e8853bfa599a2d6a0a1b7eb682ef"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.aarch64-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e5631a4ef35615de0af7df82160074d46fb553e2"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "f627c785ff6ee087858b07a7cd7ea16d646e07b65fef68cac8757cebdc17ddb7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.aarch64-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5e4ecf6c1303cd25f582d8ea2555b5f856bcfb7d"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "d4df623225d3d63c86920c46070cfd15478cfa053ee6ae7d72ada35815006b5b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.aarch64-linux-musl-cxx03-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2ff446d6ca22e752035e3183bd8d815e9094ee97"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "a4427ef8fe1ab6f0405f2e01eb0daa3d570747f90c4adc4ffb74d175a3b90226"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.aarch64-linux-musl-cxx03-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e6d6496a3317f80546f5367a8bcce168896b0091"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "2830597d1cef48aee1f41b4c7a24bdf7127f1e5a7ae02de1e0f3eb92abc31203"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.aarch64-linux-musl-cxx03-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4d331449910405bdf2eb4e227d18ed4db29d00a"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "35d9d3826a9172caefe8dcfabfc1f53dcf6ee8c9d5dc033512732d4a2d5082a8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.aarch64-linux-musl-cxx11-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3cfebd6477074d8a63684d524d847e5188d88757"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "aa0a367aef54edd4c3c72f3ccfbbab577273cdabb69f2ab4596875beadb1c10d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.aarch64-linux-musl-cxx11-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72a4129e13db74fa16fb887b0aaa981fedaa161e"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "71fe280e61d90ab7a48707488e0afcc55c085ef75cd75565fc1e773f3790ace4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.aarch64-linux-musl-cxx11-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dbb733091ab8dd21a71e0f3fbc121823c542404e"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "99ad20174d80c30a78d27c21aa5a2fb3a958fcc3e92cd1c5e7f16942aa5ec628"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.powerpc64le-linux-gnu-cxx03-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3657276eeeee2aa39d0c1bb8d23b1144d395d493"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "f12f77abbdde8b86bcdab37c2191e98e870a3fc1b9072bc139476afb384aad93"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.powerpc64le-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9003485f5bee98d4f8247f1c0967114b5d41387"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "325cb59b2be4cbd13717030d56ce88b544b97353369f4db8cab22617abcfa60b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.powerpc64le-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "476ae050082384350aac5d88e147cdc4dfad28e5"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "9c8418b63cba963af31a69a8b82920277452faa0ece855167ec33cc8c6658bc4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.powerpc64le-linux-gnu-cxx11-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2f9e887fecd6977b15c6882178336f2e73ff6d3"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "d39d97bee32f0c808966641d936b48d2f2323ee455bbb6f466bb5b16405ad9af"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.powerpc64le-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b635efde809bccd63fe83ac65a2974275f765310"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "29b4da8216169e0e5e471170734f1da672aad7385ce5a5196e31c36b2576f8a3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.powerpc64le-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "x86_64"
git-tree-sha1 = "4819cf01ca8ee86fc44b04939fb204217f24e313"
julia_version = "1.6.0"
os = "macos"

    [[GAP.download]]
    sha256 = "898abb400b34f32235758f98332e6c9bb4c6e5b9c1f7e8fbc1252701615be02e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.x86_64-apple-darwin-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "x86_64"
git-tree-sha1 = "931c035478a8fadf5ac02e063916adaf7044e003"
julia_version = "1.7.0"
os = "macos"

    [[GAP.download]]
    sha256 = "99d12daf6557f0e8295bdb03781e5a6e75ed47e4aa4dfa5a0b2874690f3651c9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.x86_64-apple-darwin-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "x86_64"
git-tree-sha1 = "5895c5176ce446c3391476f90f5c7b8d7301bf4d"
julia_version = "1.8.0"
os = "macos"

    [[GAP.download]]
    sha256 = "29b7de2e797b664fcf1919d778ec253802e469fbee99181baa2d91d2a6b59393"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.x86_64-apple-darwin-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f22414ce95e5b155d2411ebbbad27afc17a8b67"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "b0b7f6782397826151883bf004a55017b9011ea6eda108f77cd105719584074e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.x86_64-linux-gnu-cxx03-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1deaa3f9bf3d7f344f5b250abe405c9c1cb25ea6"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "ad27e2450636788237ebe14cb5e04415793547bd0bcb7e823fc0942f0032a8e2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.x86_64-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8921a02704a4eed4e4fcdf54a94042b6c71994db"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "2ce6686f05a9eba9ffda1cd1edfa91669f78a3e6bb0ca74057725b6ddad23720"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.x86_64-linux-gnu-cxx03-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e3b5de655eb0d894cadabe3de25a5b88e663b36"
julia_version = "1.6.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "04ef4f8e6a87932dad0e4aae618fd5d13cc11695c6236704c7a8e4ce45632e0c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.x86_64-linux-gnu-cxx11-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74cf3a71a1cb6cf91647db4abde69545bce87af4"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "47ffdc9785aba0f3c7405f266ae1368c5d53c532730750ef9ab6bf0f0ebe5dae"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.x86_64-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4bfc01825fe22859d03330fd4ada028661a6da5a"
julia_version = "1.8.0"
libc = "glibc"
os = "linux"

    [[GAP.download]]
    sha256 = "9b853434dcb634968ff75800ed5b3697d880f3ee91cec609980e9e8d12198c4c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.x86_64-linux-gnu-cxx11-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8f45e8de31a2c01db42114b54620c1ae5ae2f4e9"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "b34fae061003b502865082866109f5c40ff0ff65cfe8c85140683f8f1da05160"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.x86_64-linux-musl-cxx03-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2f849f05609ddb3e3929598f525f0fa5b34ee4d6"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "9057d7c0046531e93fe98ff294428ae9fb014cc2d503bd2e0e0981dafdd6a289"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.x86_64-linux-musl-cxx03-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7010466fba8dd8c48371aa6ac6f4403bdd41c95d"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "3c0a813bdc9c8431c54c247574eb3c7bd9192b2a36eb6db2b52a1f5f9b5cc93c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.x86_64-linux-musl-cxx03-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c5841b4ed417904fce37739f3e6a86bc3ea7efa0"
julia_version = "1.6.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "07570cee3b00a69646e498174ad4bd4b81f15646f287eb37f676f218d9248ffe"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.x86_64-linux-musl-cxx11-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6a15265e02a68d85442cb275519b65dda02d6cd"
julia_version = "1.7.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "31dff023b03a84509c24bfd232d03984fe0dcc03a78d71c56fa57aab34dc8723"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.x86_64-linux-musl-cxx11-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "854e0b2e0de7d648550e8c67e1acd68b3baade3b"
julia_version = "1.8.0"
libc = "musl"
os = "linux"

    [[GAP.download]]
    sha256 = "7302940aa722f47d1b1519a708591630b550b09d66e8db1882128b83dcca59fa"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.x86_64-linux-musl-cxx11-julia_version+1.8.0.tar.gz"
[[GAP]]
arch = "x86_64"
git-tree-sha1 = "c29394f4d1fce4786dd542bcc5053985d4e21499"
julia_version = "1.6.0"
os = "freebsd"

    [[GAP.download]]
    sha256 = "eca7b612177d925ebc2d1f9580a1da10d87f397bf48b57a63fcdedecc775da1e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.x86_64-unknown-freebsd-julia_version+1.6.0.tar.gz"
[[GAP]]
arch = "x86_64"
git-tree-sha1 = "4615cd8e12db9e4ef30bcbff7868c745b76c10b7"
julia_version = "1.7.0"
os = "freebsd"

    [[GAP.download]]
    sha256 = "6fe8e05c2e793085c5e014171a27af2dcc25eea9cd5a5a9486efc62ccc70564a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.x86_64-unknown-freebsd-julia_version+1.7.0.tar.gz"
[[GAP]]
arch = "x86_64"
git-tree-sha1 = "08f34e3c43202cedfaa9abf2f5c9c0203c320049"
julia_version = "1.8.0"
os = "freebsd"

    [[GAP.download]]
    sha256 = "e9ddb8547a6f0d82894b852fd97e2cf401974df1d76ef7ead83447eaba29ae56"
    url = "https://github.com/JuliaBinaryWrappers/GAP_jll.jl/releases/download/GAP-v400.1191.1+1/GAP.v400.1191.1.x86_64-unknown-freebsd-julia_version+1.8.0.tar.gz"
